name: Bug report
description: Create a report to help us improve
labels: ["bug", "needs review"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      placeholder: |
        Steps to reproduce the behavior:

        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: A clear and concise description of what you expected to happen.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: Add any other context about the problem here.
  - type: textarea
    id: technical
    attributes:
      label: Technical ideas
      placeholder: Any suspicions for cause of problem or possible solutions. Linking to specific lines of code can be helpful. Feel free to delete this section.
